version: '3.8'
services:
  spark:
    image: bde2020/spark-master:3.3.2-hadoop3
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=init_spark
    volumes:
      - ./spark-scripts:/opt/spark-scripts
  spark-worker:
    image: bde2020/spark-worker:3.3.2-hadoop3
    depends_on:
      - spark
    environment:
      - SPARK_MASTER=spark://spark:7077
    ports:
      - "8081:8081"
  dashboard:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./dashboard:/usr/share/nginx/html
